
---
title: Death and Dismemberment
layout: home
nav_order: 4
---

# **Death and Dismemberment**

So, you’ve decided to get shot. Not the choice I would have made, but here we are. Well, you are. Good luck. 

Whenever you take Lethal damage (damage suffered below 0), you’re gonna roll on the table below. On the left is the result of the severity roll, the top is the location hit or the element used. 

You gain the listed injury, as well as all the Injuries above it. The table can’t account for everything, so interpret it logically. Augments in affected locations are broken until repaired. 

Hit Location = d6

Severity = 1d12 + Lethal Damage + # of current Injuries



<img src="death.png" alt="Death and Dismemberment Table">



**Non-Lethal Damage (stun gun, black jack, etc) results in Knocked Out for X round**


## **Damage and Injuries**

Some injuries listed aren’t on the table, but can be acquired through other means, GM choice, or deliberate actions. Damage types are also here, because I can’t think of a better place. 

**Acid**: A chemical substance that dissolves some alkalis, metals and flesh. Environmentally, does 1d6 damage to the character and 1 Endurance point (see Gear section) to any equipment when entering or starting your turn in it, unless protected. 

**Blind**: Cannot see. -8 to Attack and Defence. Automatically hit by area-of-effect attacks. Permanent.

**Bleeding Out**: You take 1d4 damage every turn until healed (requiring First Aid Kit). 

**Blood Loss**: Your permanent HP is reduced by 1 for every level you possess. 

**Burned/Frozen**: Save. On success, gain an Interesting Scar. On failure roll below:



1. Lose an arm
2. Lose both arms
3. Lose a leg
4. Lose both legs
5. Lose an eye
6. Lose both legs, arms, and eyes. Blind. \


**Concussed**: Initiative is reduced to 4.

**Cracked Ribs**: Maximum health is reduced by 4 (to a minimum of 1).  

**Cryo**: Temperatures around -200°C. Sustained contact by living organics is not advisable. Even ethanol freezes at this point. Environmentally, does 1d6 damage to the character and freezes any liquid when entering or starting your turn in it, unless protected.

**Damage Reduction**: Bestowed by some of the better armors. Reduces the damage taken by the noted amount. 

**Deaf**: Cannot hear. If ambushed, always act last. Permanent.

**Disabled**: The limb becomes unusable. A disabled arm cannot hold things, dropping anything that was in that hand. A disabled leg can’t be walked on without significant assistance, cutting your movement in half. 

**Electric**: The forgotten hazard powering our world. High-amperage electricity as one would find in a utility line or lightning strike. Environmentally, does 1d6 damage to the character, and 1 Endurance point to equipment, when entering or starting your turn in it, unless protected. Being in water doubles damage, as does holding metal. 

**Fatal Wound**: You have 3 rounds to get rid of ALL your Fatal Wounds, or you die. You have a 1-in-6 chance of removing a Fatal Wound from yourself at the end of each round. An adjacent ally can attempt to remove a Fatal Wound by spending a standard action doctoring you (requiring a First Aid Kit), and then rolling under half their Intelligence score - unless they have a useful skill. You cannot take conscious or deliberate actions. Feel free to scream and flail. Oldest Fatal Wounds are removed first. 

**Fatigue**: Each point of Fatigue damage takes up 1 Inventory slot (see below). This can be healed through a Good Night’s rest.

**Fire**: The phenomena of combustion manifested through heat, light, and flame. Tends to ignite flammable things. Environmentally, does 1d6 damage when entering or starting your turn in it. Requires Dexterity test or catch fire for an additional 1d6 damage per round until extinguished. 

**Fried**: Save. If passed, gain an Interesting Scar. If failed, roll below:



1. Deaf. 
2. Lose an eye. -1 to range attacks.
3. Lose both eyes. Blind. 
4. Nervous system damaged. Permanently lose 1 from a random stat. 
5. Palsied. Permanent -2 to Attack and Defence. 
6. Lose an arm and both eyes. Blind. 

**Mangled**: Save. If passed, gain an Interesting Scar. If failed, lose a limb. 

**Mutation**: Roll on the mutation table, gain that mutation. 

**Non-lethal**: For when you don’t want to kill a bastard, but you want them to stop. Examples include fists and low amperage/high voltage electricity (stun gun). 

**Poison**: A chemical that causes injury or death to cells, tissue, organs, or DNA. Called a **Toxin** if generated by organic source, and a **Venom** if delivered through injection. Damage by specific poison. 

**Radiation**: Damage done by radiation does not affect current HP, rather the damage is done to maximum HP. Environmentally, does 1d6 damage when moving into or starting in it. 

**Scorched/Frostbite**: Cannot wear armor. Difficulty gripping and climbing. 

**Sickened**: You are unable to keep the majority of your food and medicine down. Healing from First Aid or Good Night’s Rest (see below) is halved. 

**Skull Cracked**: Save. If passed, gain an Interesting Scar. If fail, roll below:



1. Permanently lose 1 Intelligence
2. Permanently lose 1 Wisdom
3. Permanently lose 1 Charisma
4. Blurred vision. Permanently -2 to Attack and Defense. 
5. Damage to the Broca’s and Wernicke’s areas. Lose the ability to speak coherently. 
6. Coma. Unconscious. Save means recovery in 1d6 days. Failure means 1d100 days. 

**Winded**: Automatically fail Initiative tests until you rest. 

**Wracked**: Save. If passed, gain an Interesting Scar. If failed, roll below:



1. Permanently lose 1 from a random stat. 
2. Permanently lose 1 from all stats. 
3. Lose a limb and an eye. -1 to range attacks. 
4. Lose 2 from Strength and Constitution. 
5. Enfeebled. Take double damage from additional ingested poisons. 
6. Heart pain. Cannot run. 

_Are some of these a little brutal? Maybe. But this is also a world of body augments, so if your buddies can drag you off and you can come up with the cash, most are merely a nuisance._ 


## **Interesting Scars**

Twisted marks of flesh revealing a violent past. It provides a +2 bonus to Charisma while interacting with people who appreciate that sort of thing. 


