#Custom
title: Some Weird Sin SRD
description: "An online SRD for the GLoG hack Some Weird Sin, updated (hopefully) in quicker time than the PDFs"
email: wayspell.ttrpg@gmail.com
twitter_username: "@wayspell"
baseusrl: "/"

# Build Settings
theme: just-the-docs

url: https://SomeWeirdSin.github.io

aux_links:
   "": 
   - ""



